version: "3.9"
# Create a custom build that can be re-used within Docker network
x-build-goshimmer: &goshimmer_build
  context: ../../
  args:
    DOWNLOAD_SNAPSHOT: 0
services:
  peer_master:
    build: *goshimmer_build
    stop_grace_period: 1m
    environment:
      - AUTOPEERING_BINDADDRESS=0.0.0.0:14626
      - P2P_BINDADDRESS=0.0.0.0:14666
      - WEBAPI_BINDADDRESS=0.0.0.0:8080
      - DASHBOARD_BINDADDRESS=0.0.0.0:8081
      - PROFILING_BINDADDRESS=0.0.0.0:6061
      - PROMETHEUS_BINDADDRESS=0.0.0.0:9311
    command: >
      --analysis.dashboard.dev=false
      --autoPeering.entryNodes=EYsaGXnUVA9aTYL9FwYEvoQ8d1HCJveQVL7vogu6pqCP@172.23.25.107:14626
      --node.seed=base58:8q491c3YWjbPwLmF2WD95YmCgh61j2kenCKHfGfByoWi
      --node.overwriteStoredSeed=true
      --config=/run/secrets/goshimmer.config.json
      --database.directory=/app/mainnetdb
      --node.peerDBDirectory=/app/peerdb
      --mana.enableResearchVectors=false
      --blockLayer.snapshot.file=/run/secrets/goshimmer.block.snapshot.bin
      --blockLayer.snapshot.genesisNode=
      --metrics.global=true
      --metrics.local=true
      --metrics.manaResearch=false
      --node.disablePlugins=portcheck,clock,Firewall,ManaInitializer
      --node.enablePlugins=analysisServer,analysisDashboard,prometheus,spammer,WebAPIToolsBlockEndpoint,activity,snapshot,faucet,"WebAPIFaucetEndpoint"
      --prometheus.processMetrics=false
      --faucet.seed=7R1itJx5hVuo9w9hjg5cwKFmek4HMSoBDgJZN8hKGxih
      --blockLayer.startSynced=true
    secrets:
      - goshimmer.config.json
      - goshimmer.block.snapshot.bin
    volumes:
      - mainnetdb:/app/mainnetdb
      - peerdb:/app/peerdb
    ports:
      - "8080:8080/tcp" # web API
      - "8081:8081/tcp" # dashboard
      - "8061:8061/tcp" # dags visualizer
      - "9000:9000/tcp" # analysis dashboard
      - "6081:6061/tcp" # pprof
    expose:
      - 1888/tcp # analysis server
    networks:
      - goshimmer
  peer_master2:
    build: *goshimmer_build
    stop_grace_period: 1m
    environment:
      - AUTOPEERING_BINDADDRESS=0.0.0.0:14627
      - P2P_BINDADDRESS=0.0.0.0:14667
      - WEBAPI_BINDADDRESS=0.0.0.0:8070
      - DASHBOARD_BINDADDRESS=0.0.0.0:8071
      - PROFILING_BINDADDRESS=0.0.0.0:6051
      - PROMETHEUS_BINDADDRESS=0.0.0.0:9301
    command: >
      --config=/run/secrets/goshimmer.config.json
      --database.directory=/app/mainnetdb
      --node.enablePlugins="webapi tools endpoint",activity,spammer,prometheus,faucet,"WebAPIFaucetEndpoint"
      --autoPeering.entryNodes=EYsaGXnUVA9aTYL9FwYEvoQ8d1HCJveQVL7vogu6pqCP@172.23.25.107:14626
      --node.seed=base58:4ata8GcTRMJ5sSv2jQJWmSYYTHct748p3tXmCFYm7wjA
      --node.overwriteStoredSeed=true
      --blockLayer.snapshot.file=/run/secrets/goshimmer.block.snapshot.bin
      --blockLayer.snapshot.genesisNode=
      --node.disablePlugins=portcheck,clock,Firewall,ManaInitializer,DAGsVisualizer
      --prometheus.bindAddress=0.0.0.0:9311
      --prometheus.processMetrics=false
      --faucet.seed=7R1itJx5hVuo9w9hjg5cwKFmek4HMSoBDgJZN8hKGxih
      --blockLayer.startSynced=true
    secrets:
      - goshimmer.config.json
      - goshimmer.block.snapshot.bin
    ports:
      - "8070:8080/tcp" # web API
      - "8071:8081/tcp" # dashboard
      - "6071:6061/tcp" # pprof
    networks:
      - goshimmer
    depends_on:
      - peer_master
  faucet:
    build: *goshimmer_build
    stop_grace_period: 1m
    environment:
      - AUTOPEERING_BINDADDRESS=0.0.0.0:14628
      - P2P_BINDADDRESS=0.0.0.0:14668
      - WEBAPI_BINDADDRESS=0.0.0.0:8090
      - DASHBOARD_BINDADDRESS=0.0.0.0:8091
      - PROFILING_BINDADDRESS=0.0.0.0:6091
      - PROMETHEUS_BINDADDRESS=0.0.0.0:9321
    command: >
      --config=/run/secrets/goshimmer.config.json
      --database.directory=/app/mainnetdb
      --node.peerDBDirectory=/app/peerdb
      --node.seed=base58:3YX6e7AL28hHihZewKdq6CMkEYVsTJBLgRiprUNiNq5E
      --autoPeering.entryNodes=EYsaGXnUVA9aTYL9FwYEvoQ8d1HCJveQVL7vogu6pqCP@172.23.25.107:14626
      --node.overwriteStoredSeed=true
      --node.enablePlugins=bootstrap,"webAPIToolsEndpoint",faucet,activity,prometheus,spammer,"WebAPIFaucetEndpoint"
      --prometheus.bindAddress=0.0.0.0:9311
      --prometheus.processMetrics=false
      --blockLayer.snapshot.file=/run/secrets/goshimmer.block.snapshot.bin
      --blockLayer.startSynced=true
      --faucet.seed=7R1itJx5hVuo9w9hjg5cwKFmek4HMSoBDgJZN8hKGxih
      --blockLayer.snapshot.genesisNode=
      --node.disablePlugins=portcheck,clock,Firewall,ManaInitializer
    secrets:
      - goshimmer.config.json
      - goshimmer.block.snapshot.bin
    ports:
      - "8090:8090/tcp" # web API
      - "8051:8051/tcp" # dags visualizer
      - "8091:8091/tcp" # dashboard
      - "6091:6091/tcp" # pprof
    networks:
      - goshimmer
    depends_on:
      - peer_master

# Create our own network
networks:
  goshimmer:
    driver: bridge
# Named Docker volumes for data persistence
# ./run.sh removes these on exit
volumes:
  mainnetdb:
  peerdb:
  grafana-data-volume:
# read only files to load in the containers that may be shared across containers
secrets:
  goshimmer.block.snapshot.bin:
    file: ${SNAPSHOT_FILE:-./docker-network.snapshot}
  goshimmer.config.json:
    file: ${GOSHIMMER_CONFIG:-./config.docker.json}